BASE_DE_DADOS = 'base_de_dados/yeast1.dat'
#ROTULOS_ATRIBUTOS = ["LINHA", "NUC", "VAC", "POX", "ERL", "MIT", "ALM", "GVH", "MCG", "SEQUENCE NAME"]
ROTULOS_ATRIBUTOS = ["LINHA", "MCG", "GVH", "ALM", "MIT", "ERL", 'POX', "VAC", "NUC", "SEQUENCE NAME"]
ROTULOS_CLASSES = ["CYT", "NUC", "MIT", "ME3", "ME2", "ME1", "EXC", "VAC", "POX", "ERL"]